### PR TITLE
fix: restart frame not working

### LINKED ISSUE #142: pwa-chrome: Restart Frame not working
Issue Type: <b>Bug</b>

Testing microsoft/vscode#85984

Restart Frame seems to cancel the execution. Using https://github.com/roblourens/angular2-tour-of-heroes, e.g.:
image

Extension version: 2019.12.2403
VS Code version: Code - Insiders 1.41.0-insider (97855786a014be2440751b038b373c3726e11fe8, 2019-12-03T05:40:39.806Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|8.00GB (2.20GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|44%|
</details>

### PR DESCRIPTION
**Pull request by connor4312**
Previously the paused state wasn't set and we weren't in the function
after hitting "restart frame". Both the previous adapter[1] and the
Chrome devtools themselves[2] just discard the response of restart frame
and immediately stepInto(). Doing the same here appears to work well
and fixes #142.

 1. https://github.com/microsoft/vscode-chrome-debug-core/blob/d4bd01568b2bff1109bb75d80d487b5fbbc8427e/src/chrome/chromeDebugAdapter.ts#L1603-L1605
 2. https://github.com/ChromeDevTools/devtools-frontend/blob/c96ccd99f0e299d9cce23a8667eb1d35e057f7e0/front_end/sdk/DebuggerModel.js#L1382-L1385

### CODE REVIEW

File: src/test/breakpoints/breakpointsTest.ts [hunk 1]
```diff
@@ -26,19 +26,6 @@ describe('breakpoints', () => {
       p.assertLog();
     });
 
-    itIntegrates('script', async ({ r }) => {
```
Comment (dgozman) [inline src/test/breakpoints/breakpointsTest.ts]: It seems like this removal is accidental?
